<?php
namespace SerbenConnect\Services; use SerbenConnect\API\Client;
if(!defined('ABSPATH')){exit;} final class SubadquirenciaService{
 private $c;function __construct(?Client $c=null){$this->c=$c?:new Client();}
 function listarVendedores(array $q=[]):array{return $this->c->integrationGet('subadquirencia','Vendedores/listarVendedores',$q);} function vendedorPorUuid(string $u):array{return $this->c->integrationGet('subadquirencia','Vendedores/getVendedorPorUuid',['seller_uuid'=>$u]);} function vendedorPorDocumento(string $d):array{return $this->c->integrationGet('subadquirencia','Vendedores/getVendedorPorDocumento',['document'=>preg_replace('/\D+/','',$d)]);} function listarMcc():array{return $this->c->integrationGet('subadquirencia','Vendedores/listarMcc');} function criarVendedorPF(array $p):array{return $this->c->integrationPost('subadquirencia','Vendedores/criarVendedorPF',$p);} function criarVendedorPJ(array $p):array{return $this->c->integrationPost('subadquirencia','Vendedores/criarVendedorPJ',$p);}
 function listarCompradores(string $seller,array $q=[]):array{return $this->c->integrationGet('subadquirencia','Compradores/listarCompradoresPorSeller',array_merge(['seller_uuid'=>$seller],$q));} function compradorPorUuid(string $u):array{return $this->c->integrationGet('subadquirencia','Compradores/getCompradorPorUuid',['buyer_uuid'=>$u]);} function compradorPorDocumento(string $seller,string $d):array{return $this->c->integrationGet('subadquirencia','Compradores/getCompradorPorDocumento',['seller_uuid'=>$seller,'document'=>preg_replace('/\D+/','',$d)]);} function criarComprador(array $p):array{return $this->c->integrationPost('subadquirencia','Compradores/criarComprador',$p);}
 function listarTransacoes(string $seller,array $q=[]):array{return $this->c->integrationGet('subadquirencia','Transacoes/listarTransacoesPorSeller',array_merge(['seller_uuid'=>$seller],$q));} function transacaoPorUuid(string $u):array{return $this->c->integrationGet('subadquirencia','Transacoes/getTransacaoPorUuid',['transaction_uuid'=>$u]);} function transacaoPorCharge(string $u):array{return $this->c->integrationGet('subadquirencia','Transacoes/getTransacaoPorChargeUuid',['charge_uuid'=>$u]);} function criarPix(array $p,string $key=''):array{return $this->postIdem('Transacoes/criarTransacaoPix',$p,$key);} function criarBoleto(array $p,string $key=''):array{return $this->postIdem('Transacoes/criarTransacaoBoleto',$p,$key);} function criarCredito(array $p,string $key=''):array{return $this->postIdem('Transacoes/criarTransacaoCredito',$p,$key);} function estornar(array $p,string $key=''):array{return $this->postIdem('Transacoes/estornarCobranca',$p,$key);}
 function listarWebhook():array{return $this->c->integrationGet('subadquirencia','Webhooks/listarWebhook');} function salvarWebhook(array $p):array{return $this->c->integrationPost('subadquirencia','Webhooks/salvarWebhook',$p);} function removerWebhook(array $p):array{return $this->c->integrationPost('subadquirencia','Webhooks/removerWebhook',$p);} private function postIdem(string $e,array $p,string $k):array{return $this->c->integrationPost('subadquirencia',$e,$p,$k!==''?['Idempotency-Key'=>$k]:[]);}
}
